[build]
publish = ".next"
command = "npm ci && npm run build"

[build.environment]
NODE_VERSION = "20"
NODE_ENV = "production"

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image/"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
force = false
  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200
force = false
  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

# Handle API routes for Next.js on Netlify
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

# Handle Next.js pages
[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200
